### ISSUE TITLE
Netlify Deploy fails on initial clone

### ISSUE THREAD

**Issue by joseph-allen** [ines/course-starter-r#11]
Hello, this demo looks fantastic!

Out of the box, the netlify install seems to fail for reasons that aren't yet clear though.

```
11:45:38 AM: Build ready to start
11:45:40 AM: build-image version: 6c366b9e0cc38bb3f3a40b7951f398b33cac286d
11:45:40 AM: build-image tag: v3.8.1
11:45:40 AM: buildbot version: 0f3de3d7bd3ff5c1abfa729740350905f7c3f3e8
11:45:40 AM: Building without cache
11:45:40 AM: Starting to prepare the repo for build
11:45:40 AM: No cached dependencies found. Cloning fresh repo
11:45:40 AM: git clone https://github.com/joseph-allen/r-starter-test
11:45:41 AM: Preparing Git Reference refs/heads/master
11:45:41 AM: Parsing package.json dependencies
11:45:42 AM: Starting build script
11:45:42 AM: Installing dependencies
11:45:42 AM: Python version set to 2.7
11:45:43 AM: v12.18.0 is already installed.
11:45:44 AM: Now using node v12.18.0 (npm v6.14.4)
11:45:44 AM: Started restoring cached build plugins
11:45:44 AM: Finished restoring cached build plugins
11:45:44 AM: Attempting ruby version 2.7.2, read from environment
11:45:46 AM: Using ruby version 2.7.2
11:45:46 AM: Using PHP version 5.6
11:45:46 AM: Started restoring cached node modules
11:45:46 AM: Finished restoring cached node modules
11:45:46 AM: Installing NPM modules using NPM version 6.14.4
11:46:25 AM: > sharp@0.21.3 install /opt/build/repo/node_modules/sharp
11:46:25 AM: > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
11:46:27 AM: info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.0/libvips-8.7.0-linux-x64.tar.gz
11:46:29 AM: prebuild-install WARN install No prebuilt binaries found (target=12.18.0 runtime=node arch=x64 libc= platform=linux)
11:46:33 AM: make: Entering directory '/opt/build/repo/node_modules/sharp/build'
11:46:33 AM:   TOUCH Release/obj.target/libvips-cpp.stamp
11:46:33 AM:   CXX(target) Release/obj.target/sharp/src/common.o
11:46:34 AM: In file included from ../src/common.cc:27:0:
11:46:34 AM: ../src/common.h:78:16: error: ‘Handle’ is not a member of ‘v8’
11:46:34 AM:    bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
11:46:34 AM:                 ^
11:46:34 AM: ../src/common.h:78:37: error: expected primary-expression before ‘>’ token
11:46:34 AM:    bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
11:46:34 AM:                                      ^
11:46:34 AM: ../src/common.h:78:39: error: ‘obj’ was not declared in this scope
11:46:34 AM:    bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
11:46:34 AM:                                        ^
11:46:34 AM: ../src/common.h:78:56: error: expected primary-expression before ‘attr’
11:46:34 AM:    bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
11:46:34 AM:                                                         ^
11:46:34 AM: ../src/common.h:78:60: error: expression list treated as compound expression in initializer [-fpermissive]
11:46:34 AM:    bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
11:46:34 AM:                                                             ^
11:46:34 AM: ../src/common.h:79:25: error: ‘Handle’ is not a member of ‘v8’
11:46:34 AM:    std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
11:46:34 AM:                          ^
11:46:34 AM: ../src/common.h:79:46: error: expected primary-expression before ‘>’ token
11:46:34 AM:    std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
11:46:34 AM:                                               ^
11:46:34 AM: ../src/common.h:79:48: error: ‘obj’ was not declared in this scope
11:46:34 AM:    std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
11:46:34 AM:                                                 ^
11:46:34 AM: ../src/common.h:79:65: error: expected primary-expression before ‘attr’
11:46:34 AM:    std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
11:46:34 AM:                                                                  ^
11:46:34 AM: ../src/common.h:80:34: error: ‘Handle’ is not a member of ‘v8’
11:46:34 AM:    std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr);
11:46:34 AM:                                   ^
11:46:34 AM: ../src/common.h:80:55: error: expected primary-expression before ‘>’ token
11:46:34 AM:    std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr);
11:46:34 AM:                                                        ^
11:46:34 AM: ../src/common.h:80:57: error: ‘obj’ was not declared in this scope
11:46:34 AM:    std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr);
11:46:34 AM:                                                          ^
11:46:34 AM: ../src/common.h:80:74: error: expected primary-expression before ‘attr’
11:46:34 AM:    std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr);
11:46:34 AM:                                                                           ^
11:46:34 AM: ../src/common.h:81:44: error: ‘Handle’ is not a member of ‘v8’
11:46:34 AM:    template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                                             ^
11:46:34 AM: ../src/common.h:81:65: error: expected primary-expression before ‘>’ token
11:46:34 AM:    template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                                                                  ^
11:46:34 AM: ../src/common.h:81:67: error: ‘obj’ was not declared in this scope
11:46:34 AM:    template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                                                                    ^
11:46:34 AM: ../src/common.h:81:84: error: expected primary-expression before ‘attr’
11:46:34 AM:    template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                                                                                     ^
11:46:34 AM: ../src/common.h:81:37: warning: variable templates only available with -std=c++14 or -std=gnu++14
11:46:34 AM:    template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                                      ^
11:46:34 AM: ../src/common.h:81:90: error: expected ‘;’ before ‘{’ token
11:46:34 AM:    template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                                                                                           ^
11:46:34 AM: ../src/common.h:84:33: error: ‘Handle’ is not a member of ‘v8’
11:46:34 AM:    template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                                  ^
11:46:34 AM: ../src/common.h:84:54: error: expected primary-expression before ‘>’ token
11:46:34 AM:    template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                                                       ^
11:46:34 AM: ../src/common.h:84:56: error: ‘obj’ was not declared in this scope
11:46:34 AM:    template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                                                         ^
11:46:34 AM: ../src/common.h:84:73: error: expected primary-expression before ‘attr’
11:46:34 AM:    template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                                                                          ^
11:46:34 AM: ../src/common.h:84:26: warning: variable templates only available with -std=c++14 or -std=gnu++14
11:46:34 AM:    template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                           ^
11:46:34 AM: ../src/common.h:84:79: error: expected ‘;’ before ‘{’ token
11:46:34 AM:    template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                                                                                ^
11:46:34 AM: ../src/common.h:87:33: error: ‘Handle’ is not a member of ‘v8’
11:46:34 AM:    template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
11:46:34 AM:                                  ^
11:46:34 AM: ../src/common.h:87:54: error: expected primary-expression before ‘>’ token
11:46:34 AM:    template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
11:46:34 AM:                                                       ^
11:46:34 AM: ../src/common.h:87:56: error: ‘obj’ was not declared in this scope
11:46:34 AM:    template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
11:46:34 AM:                                                         ^
11:46:34 AM: ../src/common.h:87:61: error: expected primary-expression before ‘int’
11:46:34 AM:    template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
11:46:34 AM:                                                              ^
11:46:34 AM: ../src/common.h:84:26: warning: variable templates only available with -std=c++14 or -std=gnu++14
11:46:34 AM:    template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                           ^
11:46:34 AM: ../src/common.h:87:71: error: expected ‘;’ before ‘{’ token
11:46:34 AM:    template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
11:46:34 AM:                                                                        ^
11:46:34 AM: ../src/common.h:93:5: error: ‘Handle’ is not a member of ‘v8’
11:46:34 AM:      v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
11:46:34 AM:      ^
11:46:34 AM: ../src/common.h:93:26: error: expected primary-expression before ‘>’ token
11:46:34 AM:      v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
11:46:34 AM:                           ^
11:46:34 AM: ../src/common.h:93:28: error: ‘input’ was not declared in this scope
11:46:34 AM:      v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
11:46:34 AM:                             ^
11:46:34 AM: ../src/common.h:93:70: error: expected primary-expression before ‘&’ token
11:46:34 AM:      v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
11:46:34 AM:                                                                       ^
11:46:34 AM: ../src/common.h:93:71: error: ‘buffersToPersist’ was not declared in this scope
11:46:34 AM:      v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
11:46:34 AM:                                                                        ^
11:46:34 AM: ../src/common.h:93:87: error: expression list treated as compound expression in initializer [-fpermissive]
11:46:34 AM:      v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
11:46:34 AM:                                                                                        ^
11:46:34 AM: ../src/common.cc:34:20: error: redefinition of ‘bool sharp::HasAttr’
11:46:34 AM:    bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                     ^
11:46:34 AM: In file included from ../src/common.cc:27:0:
11:46:34 AM: ../src/common.h:78:8: note: ‘bool sharp::HasAttr’ previously defined here
11:46:34 AM:    bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
11:46:34 AM:         ^
11:46:34 AM: ../src/common.cc:34:16: error: ‘Handle’ is not a member of ‘v8’
11:46:34 AM:    bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                 ^
11:46:34 AM: ../src/common.cc:34:37: error: expected primary-expression before ‘>’ token
11:46:34 AM:    bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                                      ^
11:46:34 AM: ../src/common.cc:34:39: error: ‘obj’ was not declared in this scope
11:46:34 AM:    bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                                        ^
11:46:34 AM: ../src/common.cc:34:56: error: expected primary-expression before ‘attr’
11:46:34 AM:    bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                                                         ^
11:46:34 AM: ../src/common.cc:37:29: error: redefinition of ‘std::string sharp::AttrAsStr’
11:46:34 AM:    std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                              ^
11:46:34 AM: In file included from ../src/common.cc:27:0:
11:46:34 AM: ../src/common.h:79:15: note: ‘std::string sharp::AttrAsStr’ previously declared here
11:46:34 AM:    std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
11:46:34 AM:                ^
11:46:34 AM: ../src/common.cc:37:25: error: ‘Handle’ is not a member of ‘v8’
11:46:34 AM:    std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                          ^
11:46:34 AM: ../src/common.cc:37:46: error: expected primary-expression before ‘>’ token
11:46:34 AM:    std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                                               ^
11:46:34 AM: ../src/common.cc:37:48: error: ‘obj’ was not declared in this scope
11:46:34 AM:    std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                                                 ^
11:46:34 AM: ../src/common.cc:37:65: error: expected primary-expression before ‘attr’
11:46:34 AM:    std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                                                                  ^
11:46:34 AM: ../src/common.cc:40:38: error: redefinition of ‘std::vector<double> sharp::AttrAsRgba’
11:46:34 AM:    std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                                       ^
11:46:34 AM: In file included from ../src/common.cc:27:0:
11:46:34 AM: ../src/common.h:80:23: note: ‘std::vector<double> sharp::AttrAsRgba’ previously declared here
11:46:34 AM:    std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr);
11:46:34 AM:                        ^
11:46:34 AM: ../src/common.cc:40:34: error: ‘Handle’ is not a member of ‘v8’
11:46:34 AM:    std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                                   ^
11:46:34 AM: ../src/common.cc:40:55: error: expected primary-expression before ‘>’ token
11:46:34 AM:    std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                                                        ^
11:46:34 AM: ../src/common.cc:40:57: error: ‘obj’ was not declared in this scope
11:46:34 AM:    std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                                                          ^
11:46:34 AM: ../src/common.cc:40:74: error: expected primary-expression before ‘attr’
11:46:34 AM:    std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr) {
11:46:34 AM:                                                                           ^
11:46:34 AM: ../src/common.cc:654:1: error: expected ‘}’ at end of input
11:46:34 AM:  }  // namespace sharp
11:46:34 AM:  ^
11:46:34 AM: cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
11:46:34 AM: sharp.target.mk:138: recipe for target 'Release/obj.target/sharp/src/common.o' failed
11:46:34 AM: make: *** [Release/obj.target/sharp/src/common.o] Error 1
11:46:34 AM: make: Leaving directory '/opt/build/repo/node_modules/sharp/build'
11:46:34 AM: gyp ERR! build error
11:46:34 AM: gyp ERR! stack Error: `make` failed with exit code: 2
11:46:34 AM: gyp ERR! stack     at ChildProcess.onExit (/opt/buildhome/.nvm/versions/node/v12.18.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
11:46:34 AM: gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
11:46:34 AM: gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
11:46:34 AM: gyp ERR! System Linux 4.19.167+
11:46:34 AM: gyp ERR! command "/opt/buildhome/.nvm/versions/node/v12.18.0/bin/node" "/opt/buildhome/.nvm/versions/node/v12.18.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
11:46:34 AM: gyp ERR! cwd /opt/build/repo/node_modules/sharp
11:46:34 AM: gyp ERR! node -v v12.18.0
11:46:34 AM: gyp ERR! node-gyp -v v5.1.0
11:46:34 AM: gyp ERR! not ok
11:46:36 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
11:46:36 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
11:46:36 AM: npm ERR! code ELIFECYCLE
11:46:36 AM: npm ERR! errno 1
11:46:36 AM: npm ERR! sharp@0.21.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
11:46:36 AM: npm ERR! Exit status 1
11:46:36 AM: npm ERR!
11:46:36 AM: npm ERR! Failed at the sharp@0.21.3 install script.
11:46:36 AM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
11:46:36 AM: npm ERR! A complete log of this run can be found in:
11:46:36 AM: npm ERR!     /opt/buildhome/.npm/_logs/2021-07-21T10_46_36_396Z-debug.log
11:46:36 AM: Error during NPM install
11:46:36 AM: Build was terminated: Build script returned non-zero exit code: 1
11:46:36 AM: Creating deploy upload records
11:46:36 AM: Failing build: Failed to build site
11:46:36 AM: Failed during stage 'building site': Build script returned non-zero exit code: 1
11:46:36 AM: Finished processing build request in 56.316113869s
```

**Comment by joseph-allen** [comment]
The version of sharp used in this project is no longer supported in Node 12 onwards, lower versions of node are now in the end of life. See details [here](https://github.com/lovell/sharp/issues/1741)

 Fix your Netlify deploy to version 10, you can do this by setting your NODE_VERSION env variable as described [here](https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript)

**Comment by lionelvoirol** [comment]
thanks @joseph-allen !
